spring:
  datasource:
    driver-class-name: com.nysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/pet_world
    username: suporte
    password: suporte
  mvc:
    view:
      preffix: /WEB-INF/views/
      suffix: .jsp
